My nc news 7
kamiviolet/my-nc-news pull request #8
Opened 2023-05-11 09:41 UTC by kamiviolet

1. update endpoints.json
2. add new method to endpoint /api/articles/:article_id/comments
3. add test suite
- 2 tests for status 201
- 4 tests for status 400 (as it is a POST method, i decided to use 400 even if the numeric article_id is not found as it is not to GET the article but a REQUEST)

2023-05-11 10:06 UTC, yalicee requested changes
Other things to consider besides my comments:
-article_id is also a foreign key so again, a separate check that the article exists should not be necessary as a psql error will be thrown.
-a psql error will also be thrown if article_id is not a number.

2023-05-11 10:06 UTC, yalicee commented on __tests__/app.test.js
>      it('GET - status 404 - invalid numeric article_id will respond with not found.', () => {
technically this is a valid numeric article but just non existent

2023-05-11 10:06 UTC, yalicee commented on __tests__/app.test.js
> +                expect(rows[0].article_id).toBe(article_id);
SQL is not needed in testing. This is similar to the test you have above as you return back the comment object anyway. Please remove

2023-05-11 10:06 UTC, yalicee commented on __tests__/app.test.js
> +    })
This test could be considered redundant due to test above

2023-05-11 10:06 UTC, yalicee commented on __tests__/app.test.js
> +    })
This is a 404 not found test

2023-05-11 10:06 UTC, yalicee commented on __tests__/app.test.js
> +        })
Same for this one

2023-05-11 10:06 UTC, yalicee commented on controllers/comments.controller.js
> +        next(err);
Have a think about if you can move this functionality somewhere else? Perhaps in your error handlers?

2023-05-11 10:06 UTC, yalicee commented on db/seeds/utils.js
> +        return {status: 404, message: 'The username is currently not found.'}
author in the comments table is a foreign key which relates to username in the users table. A psql error will be thrown if this is violated. It is not necessary to separately check if the user exists. same for article_id

2023-05-11 10:06 UTC, yalicee commented on models/comments.model.js
> +        .then(() => validateExistingUser(comment.username))
Again no need to check if they exist

2023-05-11 10:06 UTC, yalicee requested changes
Other things to consider besides my comments:
-article_id is also a foreign key so again, a separate check that the article exists should not be necessary as a psql error will be thrown.
-a psql error will also be thrown if article_id is not a number.

2023-05-11 10:36 UTC, kamiviolet commented
> Other things to consider besides my comments: -article_id is also a foreign key so again, a separate check that the article exists should not be necessary as a psql error will be thrown. -a psql error will also be thrown if article_id is not a number.

@yalicee Sorry i am stuck... i added the extra util function to check if its a valid foreign key because if not doing so, my terminal is hanging from Jest 500s timeout... how should i organise to be able to achieve so? T_T

2023-05-12 09:20 UTC, yalicee approved these changes

2023-05-12 09:20 UTC, yalicee commented on __tests__/app.test.js
> +            .send({username: 'XXX', body: 'XXXX'})
Please change this to be a valid comment object so it's less confusing what error it is for

2023-05-12 09:20 UTC, yalicee commented on app.js
>  })
There is an opportunity to refactor this later on

2023-05-12 09:20 UTC, yalicee commented on controllers/comments.controller.js
> +            res.status(201).send({comment: comment[0]})
would prefer you to index this array in the model instead of the controller

2023-05-12 09:28 UTC, merged